FROM node:14.17-alpine as builder

WORKDIR /app

COPY ./eth-system-frontend .

RUN npm i

RUN npm run build

FROM nginx:alpine

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=builder /app/dist .
COPY --from=builder /app/nginx/frontend.conf /etc/nginx/conf.d/default.conf

EXPOSE 80 443
ENTRYPOINT ["nginx", "-g", "daemon off;"]
